name: "L2TP/IPsec VPN Client"
version: "1.0.0"
slug: "l2tp_ipsec_vpn_client"
description: "Home Assistant add-on wrapping the l2tp-ipsec-vpn-client"
url: "https://github.com/Voyanti/ha-l2tp-ipsec-vpn-client"
arch:
  - amd64
  - armv7
  - aarch64
startup: services
boot: auto
privileged: true  # Needed for IPsec / PPP kernel modules
host_network: true # So VPN traffic is managed directly on host network

# These are configuration options the user can set in the Add-on UI.
options:
  server: "vpn.example.com"
  psk: "MY_PRESHARED_KEY"
  username: "myuser"
  password: "mypassword"
  idle: "0"
  require_chap: "no"
  refuse_chap: "no"
  refuse_eap: "yes"
  refuse_pap: "no"

# Validate the user input with a JSON schema
schema:
  server: str
  psk: str
  username: str
  password: str
  idle: str
  require_chap: str
  refuse_chap: str
  refuse_eap: str
  refuse_pap: str