name: "L2TP/IPsec VPN Client"
version: "1.1.15"
slug: "l2tp_ipsec_vpn_client"
description: "Home Assistant add-on wrapping the l2tp-ipsec-vpn-client"
url: "https://github.com/Voyanti/ha-l2tp-ipsec-vpn-client/l2tp_ipsec_vpn_client"
init: false
arch:
  - amd64
  - armv7
  - aarch64
startup: services
boot: auto
privileged:
  - NET_ADMIN
  - SYS_ADMIN
host_network: true

options:
  server: "vpn.example.com"
  psk: "MY_PRESHARED_KEY"
  username: "myuser"
  password: "mypassword"
  idle: "0"
  require_chap: "no"
  refuse_chap: "no"
  refuse_eap: "yes"
  refuse_pap: "no"

schema:
  server: str
  psk: str
  username: str
  password: str
  idle: str
  require_chap: str
  refuse_chap: str
  refuse_eap: str
  refuse_pap: str